name: Build LaTeX document
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    name: Compile all LaTeX documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: doc/
          
      - name: Copy
        run: |
          mkdir out
          cp doc/main.pdf out/main.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdf
          path: out/main.pdf


  deploy_to_gh_pages:
    name: Deploy to GitHub Pages
    needs: build_latex
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PDFs artifact
        uses: actions/download-artifact@v4
        with:
          name: latex-pdf
          path: deployment_assets

      - name: List files in deployment assets (for debugging)
        run: ls -R deployment_assets

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deployment_assets
          branch: gh-pages
          clean: true